// src/frontend/react-tilt/src/public-tilts.tsx
import React, { useEffect, useState } from 'react';
import './App.css';
import { publicTilt } from './classes/publicTilt';
import { PublicTiltsService } from './services/public-tilts.service';

function PublicTilts() {
    const [publicTilts, addTilts] = useState(Array<publicTilt>(0));
    
    useEffect(() => {
        console.log("hello");
        return () => console.log("goodbye");
      }, []);
      
    useEffect(()=>{
      var publicService= new PublicTiltsService();
      var x= publicService.getUrls().subscribe(data=>{
        data.forEach( it=>{
            publicService.nrTilts(it).subscribe(a=> 
            {
              console.log("obtaining ", a );            
              addTilts((prevState:publicTilt[])=>  [...prevState, a] );
            }
            );
          });
  
      });
      return ()=> x.unsubscribe();
    },[]);//very important!



    if (publicTilts.length === 0) {
        return <> { <div>Loading</div> } </>;
    }

    return <>{
    <div>
    <h2>Public URLS {publicTilts.length} </h2>
    {publicTilts.map((tilt) => 
        (
          <div key={tilt.url}>
        <a href={`${tilt.url}`}>{tilt.url}</a>     {tilt.nrTilts}    
        </div>
        )
    )
    }
    
  </div>
    }</>
}

export default PublicTilts;

// src/frontend/AngTilt14/src/app/public-tilts/public-tilts.component.ts
import { Component, OnInit } from '@angular/core';
import { PublicTiltsService } from '../services/public-tilts.service';
import { FormArray, FormBuilder } from '@angular/forms';
import { publicTilt } from './publicTilt';
@Component({
  selector: 'app-public-tilts',
  templateUrl: './public-tilts.component.html',
  styleUrls: ['./public-tilts.component.css']
})
export class PublicTiltsComponent implements OnInit {

    profileForm = this.fb.group({
      publicUrls: this.fb.array([
        this.fb.control(new publicTilt())
      ])
    });
    
  constructor(private publicService:PublicTiltsService, private fb:FormBuilder) { 

    

  }
  get publicUrls() {
    return this.profileForm.get('publicUrls') as FormArray;
  }

  ngOnInit(): void {
    this.publicService.getUrls().subscribe(data=>{
      // window.alert(JSON.stringify(data));
      this.publicUrls.clear();
      // data.forEach(it=> this.publicUrls.push(this.fb.control(new publicTilt({url:it}))));
      data.forEach(it=>{
         this.publicService.nrTilts(it).subscribe(a=> 
          {
            console.log("obtaining ", a );            
            this.publicUrls.push(this.fb.control(a));            
          }
          );
        });

    });
  }

}

<form [formGroup]="profileForm">
<div formArrayName="publicUrls">
    <h2>Public URLS</h2>
    <!-- <button type="button" (click)="addAlias()">+ Add another alias</button> -->
  
    <div *ngFor="let alias of publicUrls.controls; let i=index">
      
      <!-- <input id="alias-{{ i }}" type="text" [formControlName]="i"/> -->

      <a name="{{publicUrls.controls[i].value.url}}" class="publicURL"  routerLink="/tilt/public/{{publicUrls.controls[i].value.url}}"   >{{publicUrls.controls[i].value.url}}</a>
      
      {{publicUrls.controls[i].value.nrTilts}}
    </div>
  </div>
</form>
